development:
  clients:
    default:
      database: <%= File.basename(PADRINO_ROOT) %>
      hosts:
        - 127.0.0.1:27017
        
test:
  clients:
    default:
      database: <%= File.basename(PADRINO_ROOT) %>_test
      hosts:
        - 127.0.0.1:27017        

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || ENV['MONGO_URL'] %>